INSERT INTO alura.unidades (descricao,endereco) VALUES
	 ('BETHA','RIO-DO-SUL'),
	 ('BETHA','CRICIUMA'),
	 ('UNIDAVI','RIO-DO-SUL'),
	 ('UNIDAVI','TAIÓ'),
	 ('UNIDAVI','ITUPORANGA'),
	 ('INFO-DIGITALLE','RIO-DO-SUL'),
	 ('INFO-DIGITALLE','TROMBUDO-CENTRAL');
